core/accounts/api/v1/urls.py
from django.urls import path, include

app_name = "api-v1"

urlpatterns = [
    path("", include("djoser.urls")),
    path("", include("djoser.urls.jwt")),
    path("", include("djoser.urls.authtoken")),
]

core/accounts/urls.py
from accounts import views
from django.contrib.auth import views as auth_views
from django.urls import path, include

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("api/v1/", include("accounts.api.v1.urls")),
]

core/blog/urls.py
from blog.feeds import LatestEntriesFeed
from blog.views import (
    BlogListView,
    BlogSingleView,
    BlogCategoryView,
    BlogSearchView,
)
from django.urls import path, include

app_name = "blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_view"),
    path("<int:pk>/", BlogSingleView.as_view(), name="single"),
    path(
        "category/<str:cat_name>/",
        BlogCategoryView.as_view(),
        name="category",
    ),
    path("tag/<str:tag_name>/", BlogListView.as_view(), name="tag_list"),
    path(
        "author/<str:author_username>/",
        BlogListView.as_view(),
        name="author_list",
    ),
    path("search/", BlogSearchView.as_view(), name="search"),
    path("rss/feed/", LatestEntriesFeed(), name="rss_feed"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
import django.contrib.auth.urls
from blog.sitemaps import BlogSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from main.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("main.urls", namespace="main")),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include(django.contrib.auth.urls)),
]

if settings.COMINGSOON:
    urlpatterns.insert(
        0,
        re_path(
            r"^", TemplateView.as_view(template_name="comingsoon.html")
        ),
    )

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

if settings.SHOW_SWAGGER:
    urlpatterns += [
        path(
            "api-auth/",
            include("rest_framework.urls", namespace="rest_framework"),
        ),
        path("schema/", SpectacularAPIView.as_view(), name="schema"),
        path(
            "swagger/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="swagger-ui",
        ),
    ]

handler400 = "core.error_views.error_400"  # bad_request
handler403 = "core.error_views.error_403"  # permission_denied
handler404 = "core.error_views.error_404"  # page_not_found
handler500 = "core.error_views.error_500"  # server_error

core/main/urls.py
from django.urls import path, include

from main.views import IndexView, AboutView, ContactView

app_name = "main"

urlpatterns = [
    path("", IndexView.as_view(), name="index_view"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("api/v1/", include("main.api.v1.urls")),
]

core/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    """
    A form that extends the default UserCreationForm to include an email field.

    Attributes:
            email (EmailField): The email field for the user's email address.
    """

    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label="Username or Email", max_length=254)

    def clean_username(self):
        username = self.cleaned_data["username"]
        return username

core/accounts/views.py
import re

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import RedirectView
from django.views.generic.edit import FormView

from .forms import CustomAuthenticationForm
from .forms import CustomUserCreationForm


class LoginView(View):
    form_class = CustomAuthenticationForm
    template_name = "accounts/login.html"

    def is_valid_email(self, email):
        email_regex = (
            r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
        )
        return re.match(email_regex, email)

    def email_to_username(self, email):
        try:
            user = User.objects.get(email=email)
            return user.username
        except User.DoesNotExist:
            return None

    def get(self, request):
        if not request.user.is_authenticated:
            form = self.form_class()
            context = {"form": form}
            return render(request, self.template_name, context)
        else:
            return redirect(reverse("main:index_view"))

    def post(self, request):
        if not request.user.is_authenticated:
            form = self.form_class(
                request=request, data=request.POST.copy()
            )
            login_data = form.data.get("username")
            is_email = self.is_valid_email(login_data)

            if is_email:
                username_from_email = self.email_to_username(login_data)
                if username_from_email:
                    form.data["username"] = username_from_email

            if form.is_valid():
                login_data = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(
                    request, username=login_data, password=password
                )

                if user is not None:
                    login(request, user)
                    messages.add_message(
                        request,
                        messages.SUCCESS,
                        f"{login_data} logged in successfully",
                    )
                    return redirect(reverse("main:index_view"))
                else:
                    messages.add_message(
                        request,
                        messages.ERROR,
                        "Sorry, we couldn't log you in",
                    )
                    return redirect(reverse("main:index_view"))
            else:
                context = {"form": form}
                return render(request, self.template_name, context)
        else:
            return redirect(reverse("main:index_view"))


class LogoutView(LoginRequiredMixin, RedirectView):
    """
    Handles user logout functionality.
    """

    pattern_name = "main:index_view"

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        messages.success(self.request, "Logged Out Successfully")
        return super().get_redirect_url(*args, **kwargs)


class SignupView(FormView):
    """
    Handles user signup functionality.
    """

    template_name = "accounts/signup.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("accounts:login")

    def is_user_exists(self, email, username):
        User = get_user_model()
        return (
            User.objects.filter(email=email).exists()
            or User.objects.filter(username=username).exists()
        )

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        username = form.cleaned_data.get("username")

        if self.is_user_exists(email, username):
            messages.error(
                self.request, "This email or username is already in use."
            )
            return self.form_invalid(form)

        form.save()
        messages.success(self.request, "User created Successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Sorry Something went wrong")
        return super().form_invalid(form)


def is_user_exists(email, username):
    """
    Checks if a user with the given email or username already exists.

    Args:
        email (str): The email address to check.
        username (str): The username to check.

    Returns:
        bool: True if a user with the given email or username exists,
        False otherwise.
    """
    return User.objects.filter(
        Q(email=email) | Q(username=username)
    ).exists()

core/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Login
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/login_css.css' %}">
{% endblock %}
{% block content %}
    <section class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
                    <h1 class="mb-3 bread">LOGIN</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:index_view' %}">Home</a></span>
                </div>
            </div>
        </div>
    </section>
    <section style="margin-bottom: 150px;">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form method="post" action="{% url 'accounts:login' %}" novalidate>
                        {% csrf_token %}
                        <!-- Username input -->
                        <div class="form-outline mb-4">
                            <input type="text" id="form3Example3" name='username' class="form-control form-control-lg"
                                   placeholder="Enter a valid Username or Email"/>
                            <label class="form-label" for="form3Example3">Username or Email</label>
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-3">
                            <input type="password" name="password" id="form3Example4"
                                   class="form-control form-control-lg"
                                   placeholder="Enter password"/>
                            <label class="form-label" for="form3Example4">Password</label>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <!-- Checkbox -->
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3"/>
                                <label class="form-check-label" for="form2Example3">
                                    Remember me
                                </label>
                            </div>
                            <a href="{% url 'accounts:password_reset' %}" class="text-warning">Forgot password?</a>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="btn btn-warning btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Login
                            </button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a
                                    href="{% url 'accounts:signup' %}"
                                    class="text-warning">Register</a>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

core/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    SignUp
{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/login_css.css' %}">
{% endblock %}
{% block content %}
    <section class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
                    <h1 class="mb-3 bread">SIGN UP</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:index_view' %}">Home</a></span>
                </div>
            </div>
        </div>
    </section>
    <section style="margin-bottom: 150px;">
        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                         class="img-fluid" alt="Sample image">
                </div>
                <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                    <form method="post" action="{% url 'accounts:signup' %}" novalidate>
                        {% csrf_token %}
                        <!-- Email input -->
                        <div class="form-outline mb-3">
                            <input type="email" id="form3Example2" name="email" class="form-control form-control-lg"
                                   placeholder="Enter your email"/>
                            <label class="form-label" for="form3Example2">Email</label>
                        </div>
                        <!-- Username input -->
                        <div class="form-outline mb-3">
                            <input type="text" id="form3Example3" name='username' class="form-control form-control-lg"
                                   placeholder="Enter a valid Username"/>
                            <label class="form-label" for="form3Example3">Username</label>
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-2">
                            <input type="password" name="password1" id="form3Example4"
                                   class="form-control form-control-lg"
                                   placeholder="Enter password"/>
                            <label class="form-label" for="form3Example4">Password</label>
                        </div>

                        <!-- Password Confirmation input -->
                        <div class="form-outline mb-1">
                            <input type="password" name="password2" id="form3Example5"
                                   class="form-control form-control-lg"
                                   placeholder="Confirm password"/>
                            <label class="form-label" for="form3Example5">Password Confirmation</label>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <!-- Checkbox -->
                            <div class="form-check mb-0">
                                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3"/>
                                <label class="form-check-label" for="form2Example3">
                                    Remember me
                                </label>
                            </div>
                        </div>

                        <div class="text-center text-lg-start mt-4 pt-2">
                            <button type="submit" class="btn btn-warning btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Register
                            </button>
                            <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account? <a
                                    href="{% url 'accounts:login' %}"
                                    class="text-warning">Login</a>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}