core/blog/api/v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    CategoryViewSet,
    PostViewSet,
    CommentListCreateAPIView,
    CommentRetrieveUpdateDestroyAPIView,
)

app_name = "api-v1"

router = DefaultRouter()

router.register(r"categories", CategoryViewSet, basename="category")
router.register(r"posts", PostViewSet, basename="post")

urlpatterns = [
    path("", include(router.urls)),
    path(
        "posts/<int:pid>/comments/",
        CommentListCreateAPIView.as_view(),
        name="post-comments",
    ),
    path(
        "comments/<int:pk>/",
        CommentRetrieveUpdateDestroyAPIView.as_view(),
        name="comment-detail",
    ),
]

core/blog/urls.py
from blog.feeds import LatestEntriesFeed
from blog.views import (
    BlogListView,
    BlogSingleView,
    BlogCategoryView,
    BlogSearchView,
)
from django.urls import path, include

app_name = "blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_view"),
    path("<int:pk>/", BlogSingleView.as_view(), name="single"),
    path(
        "category/<str:cat_name>/",
        BlogCategoryView.as_view(),
        name="category",
    ),
    path("tag/<str:tag_name>/", BlogListView.as_view(), name="tag_list"),
    path(
        "author/<str:author_username>/",
        BlogListView.as_view(),
        name="author_list",
    ),
    path("search/", BlogSearchView.as_view(), name="search"),
    path("rss/feed/", LatestEntriesFeed(), name="rss_feed"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
import django.contrib.auth.urls
from blog.sitemaps import BlogSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)
from main.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("main.urls", namespace="main")),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include(django.contrib.auth.urls)),
]

if settings.COMINGSOON:
    urlpatterns.insert(
        0,
        re_path(
            r"^", TemplateView.as_view(template_name="comingsoon.html")
        ),
    )

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

if settings.SHOW_SWAGGER:
    urlpatterns += [
        path(
            "api-auth/",
            include("rest_framework.urls", namespace="rest_framework"),
        ),
        path("schema/", SpectacularAPIView.as_view(), name="schema"),
        path(
            "swagger/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="swagger-ui",
        ),
    ]

handler400 = "core.error_views.error_400"  # bad_request
handler403 = "core.error_views.error_403"  # permission_denied
handler404 = "core.error_views.error_404"  # page_not_found
handler500 = "core.error_views.error_500"  # server_error

core/main/urls.py
from django.urls import path, include

from main.views import IndexView, AboutView, ContactView

app_name = "main"

urlpatterns = [
    path("", IndexView.as_view(), name="index_view"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("api/v1/", include("main.api.v1.urls")),
]

core/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(
        upload_to="blog/%Y/%m/%d/", default="blog/default.jpg"
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    login_require = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_date"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pk": self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.name

core/blog/forms.py
from blog.models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    """
    A form for adding comments to a blog post.

    This form allows users to submit comments with their name, email,
    subject, and message.

    Attributes:
            name (CharField): The name of the commenter.
            email (EmailField): The email address of the commenter.
            subject (CharField): The subject of the comment.
            message (CharField): The content of the comment.
    """

    class Meta:
        model = Comment
        fields = ["name", "email", "subject", "message"]

core/blog/api/v1/views.py
from blog.models import Category, Post, Comment
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics, viewsets, permissions
from rest_framework.filters import SearchFilter, OrderingFilter

from blog.api.v1.paginations import PostPagination
from blog.api.v1.serializers import (
    CategorySerializer,
    PostSerializer,
    CommentSerializer,
)


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["name"]
    ordering_fields = ["name"]


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category", "status"]
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = PostPagination

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class CommentListCreateAPIView(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["post"]

    def perform_create(self, serializer):
        serializer.save(post_id=self.kwargs.get("pid"))


class CommentRetrieveUpdateDestroyAPIView(
    generics.RetrieveUpdateDestroyAPIView
):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["post"]

core/blog/views.py
from blog.forms import CommentForm
from blog.models import Post, Comment
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin


class BlogListView(ListView):
    model = Post
    template_name = "blog/blog-home.html"
    context_object_name = "posts"
    paginate_by = 2

    def get_queryset(self):
        queryset = (
            super()
            .get_queryset()
            .filter(status=1, published_date__lte=timezone.now())
        )
        cat_name = self.kwargs.get("cat_name")
        author_username = self.kwargs.get("author_username")
        tag_name = self.kwargs.get("tag_name")
        if cat_name:
            queryset = queryset.filter(category__name=cat_name)
        if author_username:
            queryset = queryset.filter(author__username=author_username)
        if tag_name:
            queryset = queryset.filter(tags__name=tag_name)
        return queryset


class BlogSingleView(FormMixin, DetailView):
    model = Post
    template_name = "blog/blog-single.html"
    context_object_name = "post"
    form_class = CommentForm

    def get_success_url(self):
        return self.request.path

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_post = self.object
        if (
            not current_post.login_require
            or self.request.user.is_authenticated
        ):
            context["comments"] = Comment.objects.filter(
                post=current_post.id, approved=True
            )
            context["form"] = self.get_form()
            current_post.counted_views += 1
            current_post.save()
        else:
            return redirect("accounts:login")
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.save()
        messages.success(
            self.request, "Your Comment Submitted Successfully"
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Your Comment Didnt Submitted")
        return super().form_invalid(form)


class BlogCategoryView(ListView):
    model = Post
    template_name = "blog/blog-home.html"
    context_object_name = "posts"
    paginate_by = 3

    def get_queryset(self):
        cat_name = self.kwargs.get("cat_name")
        return (
            super()
            .get_queryset()
            .filter(
                status=1,
                published_date__lte=timezone.now(),
                category__name=cat_name,
            )
        )


class BlogSearchView(ListView):
    model = Post
    template_name = "blog/blog-home.html"
    context_object_name = "posts"
    paginate_by = 3

    def get_queryset(self):
        queryset = (
            super()
            .get_queryset()
            .filter(status=1, published_date__lte=timezone.now())
        )
        search_query = self.request.GET.get("search")
        if search_query:
            queryset = queryset.filter(
                Q(content__contains=search_query)
                | Q(title__contains=search_query)
            )
        return queryset

core/blog/templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Blog Home
{% endblock %}
{% block content %}
    <section class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
                    <h1 class="mb-3 bread">Blog Home</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:index_view' %}">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                            href="{% url 'blog:blog_view' %}">Blog
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section ftco-project" id="projects-section">
        <div class="container">
            <div class="row justify-content-center pb-5">
                <div class="col-md-12 heading-section text-center ftco-animate">
                    <h1 class="big big-2">OUR BLOG</h1>
                    <h2 class="mb-4">WELCOME TO</h2>
                </div>
            </div>
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-6">
                        <div class="project img ftco-animate d-flex justify-content-center align-items-center"
                             style="background-image: url({{ post.image.url }});">
                            <div class="overlay"></div>
                            <div class="text text-center p-4">
                                <h3><a href="{% url 'blog:single' pk=post.id %}">{{ post.title }}</a></h3>
                                <span>{{ post.author.username }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination justify-content-center">
                {% if is_paginated %}
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

core/blog/templates/blog/blog-latest-posts.html
{% load static %}
<section class="ftco-section" id="blog-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-5">
            <div class="col-md-7 heading-section text-center ftco-animate">
                <h1 class="big big-2">Blog</h1>
                <h2 class="mb-4">Latest Posts</h2>
            </div>
        </div>
        <div class="row d-flex">
            {% for post in posts %}
                <div class="col-md-4 d-flex ftco-animate">
                    <div class="blog-entry justify-content-end">
                        <a href="{% url 'blog:single' pk=post.id %}" class="block-20"
                           style="background-image: url({{ post.image.url }});">
                        </a>
                        <div class="text mt-3 float-right d-block">
                            <div class="d-flex align-items-center mb-3 meta">
                                <p class="mb-0">
                                    <span class="mr-2">{{ post.published_date }}</span>
                                    <a href="{% url 'blog:single' pk=post.id %}"
                                       class="mr-2">{{ post.author.username }}</a>
                                </p>
                            </div>
                            <h3 class="heading"><a href="{% url 'blog:single' pk=post.id %}">{{ post.title }}</a></h3>
                            <p>{{ post.content|truncatewords:10|safe }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

core/blog/templates/blog/blog-popular-posts.html
{% load static %}
<div class="sidebar-box ftco-animate">
    <h3 class="heading-sidebar">Popular Posts</h3>
    {% for post in posts %}
        <div class="block-21 mb-4 d-flex">
            <a href="{% url 'blog:single' pk=post.id %}" class="blog-img mr-4"
               style="background-image: url({{ post.image.url }});"></a>
            <div class="text">
                <h3 class="heading"><a href="{% url 'blog:single' pk=post.id %}">{{ post.title }}</a></h3>
                <div class="meta">
                    <div><a href="{% url 'blog:single' pk=post.id %}"><span
                            class="icon-calendar"></span>{{ post.published_date }}</a></div>
                    <div><a href="{% url 'blog:single' pk=post.id %}"><span
                            class="icon-person"></span>{{ post.author.username }}</a></div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

core/blog/templates/blog/blog-post-categories.html
{% load static %}
<div class="sidebar-box ftco-animate">
    <h3 class="heading-sidebar">Categories</h3>
    <ul class="categories">
        {% for category in categories %}
            <li><a href="{% url 'blog:category' cat_name=category.name %}">{{ category.name }}
                <span>({{ category.post_set.count }})</span></a></li>
        {% endfor %}
    </ul>
</div>

core/blog/templates/blog/blog-search.html
{% load static %}
<div class="sidebar-box">
    <form action="{% url 'blog:search' %}" method="post" novalidate class="search-form">
        {% csrf_token %}
        <div class="form-group">
            <span class="icon icon-search"></span>
            <input type="text" class="form-control" name="search" placeholder="Type a keyword and hit enter">
        </div>
    </form>
</div>

core/blog/templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block title %}
    Blog-single
{% endblock %}
{% block content %}

    <section class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
                    <h1 class="mb-3 bread">Blog Single Post</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:index_view' %}">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                            href="{% url 'blog:blog_view' %}">Blog <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <p>
                        <img src="{{ post.image.url }}" alt="" class="img-fluid">
                    </p>
                    <h2 class="mb-3">{{ post.title }}</h2>
                    <p>{{ post.content|safe }}</p>

                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        <div class="tagcloud">
                            {% for cat in post.category.all %}
                                <a href="#" class="tag-cloud-link">{{ cat.name }}</a>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="about-author d-flex p-4 bg-dark">
                        <div class="desc">
                            <h3>Author: {{ post.author.username }}</h3>
                            <p>{{ post.author.get_full_name }}</p>
                            <div class="meta" style="color: #ffbd39;"><p>Published
                                Date: {{ post.published_date|naturalday }}</p></div>

                        </div>
                    </div>
                    {% include 'blog/comments.html' %}
                </div>
                <div class="col-lg-4 sidebar ftco-animate">
                    {% include 'blog/blog-search.html' %}
                    {% postcategories %}
                    {% popularposts %}
                    {% include 'blog/blog-tags.html' %}
                </div>
            </div>
    </section>

{% endblock %}

core/blog/templates/blog/blog-tags.html
{% load static %}
<div class="sidebar-box ftco-animate">
    <h3 class="heading-sidebar">Tag Cloud</h3>
    <div class="tagcloud">
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:tag_list' tag_name=tag.name %}" class="tag-cloud-link">{{ tag.name }}</a>
        {% endfor %}
    </div>
</div>

core/blog/templates/blog/comments.html
{% load static %}
{% load humanize %}
<div class="pt-5 mt-5">
    <h3 class="mb-5">{{ comments|length }} Comments</h3>
    <ul class="comment-list">
        {% for comment in comments %}
            <li class="comment">
                <div class="vcard bio">
                    <img src="{% static 'images/c1.jpg' %}" alt="Image placeholder">
                </div>
                <div class="comment-body">
                    <h3>{{ comment.name }}</h3>
                    <div class="meta">{{ comment.created_date|naturalday }}</div>
                    <p>{{ comment.message }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
    <!-- END comment-list -->

    <div class="comment-form-wrap pt-5">
        <h3 class="mb-5">Leave a comment</h3>
        <form method="post" action="{% url 'blog:single' pk=post.id %}" class="p-5 bg-dark" novalidate>
            {% csrf_token %}
            <input type="hidden" name="post" value="{{ post.id }}">
            {% if request.user.is_authenticated %}
                <input type="hidden" name="name" value="{{ request.user.username }}">
                <input type="hidden" name="email" value="{{ request.user.email }}">
            {% else %}
                <div class="form-group">
                    <label for="name">Name *</label>
                    <input type="text" class="form-control" id="name" name="name" required="required"
                           data-validation-required-message="Please enter your name">
                </div>
                <div class="form-group">
                    <label for="email">Email *</label>
                    <input type="email" class="form-control" id="email" name="email" required="required"
                           data-validation-required-message="Please enter your email">
                </div>
            {% endif %}
            <div class="form-group">
                <label for="subject">Subject</label>
                <input name="subject" id="subject" cols="30" rows="10" class="form-control" required="required"
                       data-validation-required-message="Please enter a subject"></input>
            </div>
            <div class="form-group">
                <label for="message">Message</label>
                <textarea name="message" id="message" cols="30" rows="10" class="form-control" required="required"
                          data-validation-required-message="Please enter your message"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
            </div>
        </form>
    </div>
</div>